FROM python:3.6
COPY modeling/* /notebook/code/
WORKDIR /notebook/code
RUN pip install -r requirements.txt
CMD jupyter notebook --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''